CREATE TABLE Anagrafica(
	idAnagrafica INT IDENTITY PRIMARY KEY NOT NULL,
	Cognome NVARCHAR(20) NOT NULL,
	Nome NVARCHAR(20) NOT NULL,
	Indirizzo NVARCHAR(200) NOT NULL,
	Citta NVARCHAR(100) NOT NULL,
	CAP NVARCHAR(5) NOT NULL,
	Codice_Fiscale NVARCHAR(16) NOT NULL
);